package cmsstore

// const BLOCK_STATUS_DELETED = "deleted"
const BLOCK_STATUS_DRAFT = "draft"
const BLOCK_STATUS_ACTIVE = "active"
const BLOCK_STATUS_INACTIVE = "inactive"

const ERROR_EMPTY_ARRAY = "array cannot be empty"
const ERROR_EMPTY_STRING = "string cannot be empty"
const ERROR_NEGATIVE_NUMBER = "number cannot be negative"

const COLUMN_ALIAS = "alias"
const COLUMN_CANONICAL_URL = "canonical_url"
const COLUMN_CONTENT = "content"
const COLUMN_CREATED_AT = "created_at"
const COLUMN_EDITOR = "editor"
const COLUMN_ID = "id"
const COLUMN_HANDLE = "handle"
const COLUMN_MEMO = "memo"
const COLUMN_META_DESCRIPTION = "meta_description"
const COLUMN_META_KEYWORDS = "meta_keywords"
const COLUMN_META_ROBOTS = "meta_robots"
const COLUMN_METAS = "metas"
const COLUMN_NAME = "name"
const COLUMN_PAGE_ID = "page_id"
const COLUMN_SITE_ID = "site_id"
const COLUMN_SOFT_DELETED_AT = "soft_deleted_at"
const COLUMN_STATUS = "status"
const COLUMN_TYPE = "type"
const COLUMN_TEMPLATE_ID = "template_id"
const COLUMN_TITLE = "title"
const COLUMN_UPDATED_AT = "updated_at"

// const PAGE_STATUS_DELETED = "deleted"
const PAGE_STATUS_DRAFT = "draft"
const PAGE_STATUS_ACTIVE = "active"
const PAGE_STATUS_INACTIVE = "inactive"

const PAGE_EDITOR_BLOCKAREA = "blockarea"
const PAGE_EDITOR_BLOCKEDITOR = "blockeditor"
const PAGE_EDITOR_CODEMIRROR = "codemirror"
const PAGE_EDITOR_HTMLAREA = "htmlarea"
const PAGE_EDITOR_MARKDOWN = "markdown"
const PAGE_EDITOR_TEXTAREA = "textarea"

// const TEMPLATE_STATUS_DELETED = "deleted"
const TEMPLATE_STATUS_DRAFT = "draft"
const TEMPLATE_STATUS_ACTIVE = "active"
const TEMPLATE_STATUS_INACTIVE = "inactive"
