package shared

const KeyAdminHomeURL = "admin_home_uRL"
const KeyEndpoint = "endpoint"
const PathHome = "/"

const PathBlocksBlockCreate = "/blocks/block-create"
const PathBlocksBlockDelete = "/blocks/block-delete"
const PathBlocksBlockManager = "/blocks/block-manager"
const PathBlocksBlockUpdate = "/blocks/block-update"
const PathMenusMenuCreate = "/menus/menu-create"
const PathMenusMenuDelete = "/menus/menu-delete"
const PathMenusMenuManager = "/menus/menu-manager"
const PathMenusMenuUpdate = "/menus/menu-update"
const PathPagesPageCreate = "/pages/page-create"
const PathPagesPageDelete = "/pages/page-delete"
const PathPagesPageManager = "/pages/page-manager"
const PathPagesPageUpdate = "/pages/page-update"
const PathSitesSiteCreate = "/sites/site-create"
const PathSitesSiteDelete = "/sites/site-delete"
const PathSitesSiteManager = "/sites/site-manager"
const PathSitesSiteUpdate = "/sites/site-update"
const PathTemplatesTemplateCreate = "/templates/template-create"
const PathTemplatesTemplateDelete = "/templates/template-delete"
const PathTemplatesTemplateManager = "/templates/template-manager"
const PathTemplatesTemplateUpdate = "/templates/template-update"
const PathTranslationsTranslationCreate = "/translations/translation-create"
const PathTranslationsTranslationDelete = "/translations/translation-delete"
const PathTranslationsTranslationManager = "/translations/translation-manager"
const PathTranslationsTranslationUpdate = "/translations/translation-update"

const ERROR_LOGGER_IS_NIL = "logger cannot be nil"
const ERROR_STORE_IS_NIL = "store cannot be nil"
