package shared

const KeyAdminHomeURL = "admin_home_uRL"
const KeyMediaManagerURL = "media_manager_url"
const KeyPaddingTopPx = "padding_top_px"
const KeyPaddingRightPx = "padding_right_px"
const KeyPaddingBottomPx = "padding_bottom_px"
const KeyPaddingLeftPx = "padding_left_px"
const KeyEndpoint = "endpoint"
const PathHome = "/"

const PathBlocksBlockCreate = "/blocks/block-create"
const PathBlocksBlockDelete = "/blocks/block-delete"
const PathBlocksBlockManager = "/blocks/block-manager"
const PathBlocksBlockUpdate = "/blocks/block-update"
const PathBlocksBlockVersioning = "/blocks/block-versioning"
const PathMenusMenuCreate = "/menus/menu-create"
const PathMenusMenuDelete = "/menus/menu-delete"
const PathMenusMenuManager = "/menus/menu-manager"
const PathMenusMenuUpdate = "/menus/menu-update"
const PathMenusMenuVersioning = "/menus/menu-versioning"
const PathPagesPageCreate = "/pages/page-create"
const PathPagesPageDelete = "/pages/page-delete"
const PathPagesPageManager = "/pages/page-manager"
const PathPagesPageUpdate = "/pages/page-update"
const PathPagesPageVersioning = "/pages/page-versioning"
const PathSitesSiteCreate = "/sites/site-create"
const PathSitesSiteDelete = "/sites/site-delete"
const PathSitesSiteManager = "/sites/site-manager"
const PathSitesSiteUpdate = "/sites/site-update"
const PathSitesSiteVersioning = "/sites/site-versioning"
const PathTemplatesTemplateCreate = "/templates/template-create"
const PathTemplatesTemplateDelete = "/templates/template-delete"
const PathTemplatesTemplateManager = "/templates/template-manager"
const PathTemplatesTemplateUpdate = "/templates/template-update"
const PathTemplatesTemplateVersioning = "/templates/template-versioning"
const PathTranslationsTranslationCreate = "/translations/translation-create"
const PathTranslationsTranslationDelete = "/translations/translation-delete"
const PathTranslationsTranslationManager = "/translations/translation-manager"
const PathTranslationsTranslationUpdate = "/translations/translation-update"
const PathTranslationsTranslationVersioning = "/translations/translation-versioning"

const ERROR_LOGGER_IS_NIL = "logger cannot be nil"
const ERROR_STORE_IS_NIL = "store cannot be nil"
